### ISSUE TITLE
Xatlas path error on Windows

### ISSUE THREAD

**Issue by Naxela** [mattedicksoncom/blender-xatlas#11]
Hi, and thanks for a wonderful addon!

I've been working on adding Xatlas lightmapping as an unwrapping option for my addon [The Lightmapper](https://github.com/Naxela/The_Lightmapper) when your Blender Xatlas addon is detected, although I stumpled on a problem upon using it that I think might be because of some paths issues where Windows seems to break spaces into new arguments, such as "_C:\Users\Username\AppData\Roaming\Blender Foundation\Blender_" gets split into "_C:\Users\Alexander\AppData\Roaming\Blender_" and "_Foundation\Blender_", which gives an error. I think I solved it on Windows by adding formatting the xatlas_path variable:

https://github.com/mattedicksoncom/blender-xatlas/blob/28a15dfbdd774222fa0f1b6e9b92567760a98a33/addons/blender_xatlas/__init__.py#L493

with:

```python
xatlas_process = subprocess.Popen(
    r'"{}"'.format(xatlas_path) + ' ' + arguments_string,
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    shell=True
)
```

I wanted to push a commit to your addon, but I'm unsure if this might break on Linux, and I don't have the possibility to test it sadly, although I don't think it should be a problem

I hope it might help anyway, and thanks!

**Comment by mattedicksoncom** [comment]
Hi, thanks so much for the catch.
I imagine this has probably made the addon unusable for almost everyone that has tried it!

The change works fine on Linux, so I'll update straight away.

Thanks again (Also thanks for The Lightmapper)

**Comment by Naxela** [comment]
Hi, thanks for the patch and happy to help

![image](https://user-images.githubusercontent.com/5429817/89865410-f5547700-dbad-11ea-87f2-c8f34c7db297.png)

I've added direct support for your addon in The Lightmapper once it's detected, although I had to copy and modify some code in order to make it work in background mode, as I couldn't get the context thing to work on object modes (Blenders context mode is in general a little strange), but it works.

Thanks again!
